@startuml

package App{
 package Model {
    class User{
        -name
        -email
    }
note right: php artisan make:filament-resource UserResource --generate
}
package migration{
    class Create_User{
        -id
        -name 
    }
note left: php artisan make:filament-resource UserResource --generate
}
package filament_resource{
    class UserResource{
        +test
    }
note right: php artisan make:filament-resource UserResource --generate
}

}



@enduml